# Generated by Django 2.0 on 2018-08-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_profiler_vmprof', '0006_auto_20180227_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestprofile',
            name='peak_rss_use',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
